replicaCount: 10
image:
  repository: omerbh7/fastapi-helm-argocd
  tag: "fe82d69"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: false
  host: fastapi.local
  path: /
