replicaCount: 10
image:
  repository: omerbh7/fastapi-helm-argocd
  tag: "c3fe3a2"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: false
  host: fastapi.local
  path: /
